/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Agar Culture": "琼脂培养",
    "Explore": "探索",
    "Archives": "档案",
    "Progress:": "进度:",
    "Save Game": "保存游戏",
    "Just Now": "就是现在",
    "Last Saved:": "最近保存:",
    "SAVES": "保存",
    "Import Game": "导入存档",
    "Export Game": "导出存档",
    "ASSETS": "资源",
    "Off": "关",
    "On": "开",
    "sec.": "秒.",
    "SETTINGS": "设置",
    "Display Format": "显示格式",
    "ABOUT": "关于",
    "All images in the game are hand-drawn, hand-edited, or obtained from open-source image sites. Credits go to: Pexels, Unsplash, Pixabay, Rawpixel, Wikimedia Commons, SVGRepo, iNaturalist, PickPik, Picryl, publicdomainpictures.net, freeimages.com, Font Awesome, Game-icons.net, and CC0 Research Journals.": "游戏中的所有图像都是手绘的，手工编辑的，或者从开源图像网站获得的。感谢：Pexels， Unsplash, Pixabay, Rawpixel, Wikimedia Commons, SVGRepo, iNaturalist, PickPik, Picryl, publicdomainpictures, freeimages.com, Font Awesome, Game-icons.net和CC0 Research Journals。",
    "BIOTOMATA is a semi-active, story-based incremental game, written and made over the last several months for my Final Year Project. It's been a really fun learning process, and I hope you'll have just as much fun playing the game as I did making it!": "《BIOTOMATA》是一款半活跃的基于故事的增量游戏，是我在过去几个月为最后一年的项目编写和制作的。这是一个非常有趣的学习过程，我希望你在玩游戏时也能像我制作游戏时一样开心！",
    "Autosave Interval (s)": "自动保存间隔（秒）",
    "Disable for better performance": "禁用以获得更好的性能",
    "Double Click to Mutate": "双击可进行变异",
    "Endings Found": "发现的结局",
    "Exploration Image Filters": "探索图像滤波器",
    "Hi, welcome to the about screen! This is where I ramble a little about the game :D": "嗨，欢迎来到关于页面！下面是我对游戏的一些介绍",
    "INFO": "信息",
    "May help prevent misclicks": "可能有助于防止误点击",
    "Mom and Dad <3": "妈妈和爸爸<3",
    "My Uni faculty, for letting em build this game for my FYP": "我的大学老师们，让他们为我的五年计划制作这款游戏",
    "Render Dynamic Stars": "渲染动态星星",
    "Set to '0' for 'Never'": "设置为“0”表示“从不”",
    "SPECIAL THANKS": "特别感谢",
    "Time Format": "时间格式",
    "Time in Run": "运行时间",
    "Total Biomatter Spent": "总生物物质消耗",
    "Total Enemies Defeated": "击败敌人总数",
    "Unique Enemies Defeated": "打败的独特敌人",
    "YOU, for helping me playtest the game before official launch!": "感谢你在正式发布前帮助我测试游戏！",
    "Exploring...": "探索中...",
    "Blocker Type:": "拦截器类型:",
    "COMBAT": "战斗",
    "ERROR": "错误",
    "Resolve": "解决",
    "OBSTACLE DETECTED": "检测到障碍物",
    "A wriggling mass. Blocks path forward. Easy to defeat.": "一团蠕动的东西。阻挡前进的道路。很容易被打败。",
    "FIGHT": "战斗",
    "PREPARE": "准备",
    "Simple Bacterium": "简单的细菌",
    "Initiates combat.": "发起战斗。",
    "Feeble Hit": "微弱的打击",
    "NO STATUS ANOMALIES": "暂无异常状态",
    "Basic Attack": "基础攻击",
    "Deal a weak blow of [0.5×PWR] PHYS damage.": "造成[0.5×能量]微弱的物理伤害。",
    "Perform a basic attack for [1×PWR] PHYS damage.": "执行一个基本的[1×能量]物理伤害攻击。",
    "EVENT": "事件",
    "\"Novelle\"": "\“中篇小说\”",
    "A Lil' Twist in the Helix": "螺旋里的小螺旋",
    "Apex Anomaly": "顶点异常",
    "Bad Meat": "坏肉",
    "Bigger than the Page": "比页面更大",
    "Biohacking 101": "生物黑客101",
    "Complete a run as the 1st Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第一个突变阶段的任务",
    "Complete a run as the 1st Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下完成第一个突变阶段的任务",
    "Complete a run as the 2nd Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第2个突变阶段的任务",
    "Complete a run as the 2nd Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下，完成第二个突变阶段的任务",
    "Complete a run as the 3rd Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第三个突变阶段的任务",
    "Complete a run as the 3rd Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下完成第三个突变阶段的任务",
    "Complete a run as the 4th Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第4个突变阶段的任务",
    "Complete a run as the 4th Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下，完成第4个突变阶段的任务",
    "Complete a run as the 5th Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第五次变异阶段的任务",
    "Complete a run as the 5th Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下完成第五次变异阶段的任务",
    "Complete a run as the 6th Mutation Stage after fully mutating all parts": "在第6个变种阶段中完成所有变种",
    "Complete a run as the 6th Mutation Stage without fully mutating all parts": "在没有完全变异所有部件的情况下完成第六次变异阶段",
    "Creature Comforts": "物质享受",
    "Critical Biomass": "关键的生物量",
    "Defeat your first enemy": "打败你的第一个敌人",
    "Digesting the Data": "消化数据",
    "EVENT": "事件",
    "Evolutionary Arms Race (And You Have Many)": "进化军备竞赛（你有很多）",
    "Extinction Event": "灭绝事件",
    "From Slime to Sublime": "从粘液到崇高",
    "Goo-d for Growth": "促进增长",
    "Grown Beyond Containment": "超出控制范围",
    "Hungry Hungry Nova": "饥饿的新星",
    "Imposter Syndrome": "冒名顶替者综合症",
    "It Knows No Shore": "它不知道海岸",
    "Matter Matters": "重要事项",
    "Micro to Macro": "从微观到宏观",
    "Oops, My Pseudopod Slipped": "哎呀，我的假脚滑了",
    "Peer Review Not Required": "不需要同行评议",
    "Pseudopod-ful of Biomatter": "充满生物物质的假足",
    "Recontainment": "再封锁",
    "Splice of Life": "生命的拼接",
    "Sunseeker": "圣汐",
    "Survival of the Fittest (Not Your Enemies)": "适者生存（不是你的敌人）",
    "The End?": "结局？",
    "The Quiet Cure": "安静的治疗",
    "The Red Trail": "红色小径",
    "The Surface Beckons": "水面在召唤",
    "This Is How You Get Superpowers": "这就是你获得超能力的方式",
    "Too Big for Boxes": "盒子太大",
    "Unnatural Selection": "不自然的选择",
    "Violence Is Occasionally The Answer": "暴力有时是解决办法",
    "Well, They Started It": "好吧，是他们挑起的",
    "You Are Become Death": "你变成了死神",
    "Hunger": "饥饿",
    "FEED": "喂食",
    "The journey is long. The BODY tires. Seek SUSTENANCE.": "路途漫长。身体疲倦了。寻找食物。",
    "Unlocks FLESH. Unlocks SCAVENGING.": "解锁肉体。解锁拾荒。",
    "Affects:": "影响:",
    "BODY": "身体",
    "BIOMATTER Scavenging Speed": "生物物质拾荒速度",
    "Combat Max Health [via VIT]": "战斗最大生命值[通过 活力]",
    "Combat VITALITY": "战斗活力",
    "Endoplasm": "内质",
    "Resources": "资源",
    "Scavenge": "拾荒",
    "UNICELLULAR": "单细胞",
    "Scavenging...": "拾荒中...",
    "Explored Area Remaining Resources:": "探索区域剩余资源:",
    "Ciliate Protozoan": "纤毛原生动物",
    "Fast approaching entity. Appears hostile.": "快速接近的实体。看起来很有敌意。",
    "Ciliary Sweep": "纤毛扫荡",
    "Deal 3 consecutive hits of [0.3×DEX] PHYS damage.": "造成连续3次[0.3×灵巧]的物理伤害。",
    "/s": "/秒",
    "Peril ahead. Must forge STRENGTH. MASTERY is key.": "前方有危险。必须锻造力量。精通是关键。",
    "Threats": "风险",
    "TRAIN": "训练",
    "Unlocks LIMBS. Unlocks MOVESETS.": "解锁肢体。解锁招式集。",
    "(NEW!)": "(新!)",
    "STRENGTH": "力量",
    "Combat": "战斗",
    "MISC. STATS": "其它属性",
    "Add to Moveset": "添加到招式集",
    "AP Regen per Sec.": "每秒回复AP",
    "Available Moves": "可用招式",
    "Base Cooldown:": "基础冷却时间:",
    "Combat PHYS Crit. Damage [via POWER]": "战斗物理暴击。伤害[通过 能量]",
    "Combat POWER": "战力",
    "Current Moveset (": "当前招式集(",
    "Edit Moveset": "编辑招式集",
    "Move Cooldown Speed Boost": "移动冷却速度提升",
    "Phys Crit. Chance": "物理暴击。概率",
    "Phys Crit. Damage": "物理暴击。伤害",
    "Pseudopodia": "伪足",
    "Remove from Moveset": "移出招式集",
    "Select a move to view details.": "选择招式查看详情",
    "Moveset Full!": "招式集已满！",
    "Continue on. Skips for remaining run.": "继续。跳过剩余的运行。",
    "EXERT PRESSURE. SHATTER IT.": "施加压力。击碎它。",
    "Fracture": "断裂",
    "In Another Life": "另一种生活",
    "Prepare": "准备",
    "Requires 25 BODY. Unlocks shortcut.": "需要25个身体。解锁快捷方式。",
    "Requires immense force.": "需要巨大的力量。",
    "Weakness. In the glass. A quick escape?": "虚弱。在玻璃杯里。快速逃离？",
    "Apex predator. Colossal and sturdy. Challenging.": "顶级捕食者。巨大而坚固。具有挑战性。",
    "Consider": "考虑一下",
    "Damage the enemy with PURE dmg and heal self for [0.2×VIT] per second over 10 seconds.": "对敌人造成纯伤害并治疗自己，持续[0.2×活力] /秒，持续10秒",
    "Engulf": "吞噬",
    "Giant Amoeba": "巨型变形虫",
    "MOVESET": "招式集",
    "wisely.": "明智地。",
    "Giant Amoeba, Defeated": "巨型变形虫，已被击败",
    "PRESS ON": "继续前进",
    "The Colossus falls. A new path opens.": "巨像倒下了。一条新的道路开启了。",
    "Incubator": "孵化器",
    "Reset": "重置",
    "XP Gained |": "获得经验 |",
    "Unlocks QUANTUM SHIFT.": "解锁量子转变。",
    "Achievement Points": "成就点数",
    "Astral Embers?": "星体余烬?",
    "Begin Quantum Shift": "开始量子转变",
    "Cascade Lv.": "级联等级",
    "Consider REST?": "考虑休息？",
    "Enemies Defeated": "击败敌人",
    "General Stats": "常规统计",
    "Level Change:": "等级变更：",
    "Preview": "预览",
    "Preview Cascade": "预览级联",
    "Reset for": "重置为",
    "Reset Yield": "重置产量",
    "Respite": "暂缓",
    "Weary. Faltering. Futures stretch on. The CASCADE beckons.": "疲倦。摇摇欲坠。未来还在继续。瀑布在向你招手。",
    "XP to Next Level": "到下一级的经验值",
    "Ascension": "转生",
    "BIOGENESIS": "生物起源",
    "Continue >>": "继续 >>",
    "LEVEL": "等级",
    "Lv.": "等级",
    "Mastery": "精通",
    "Origins": "起源",
    "Preview Mode": "预览模式",
    "PYRE": "火堆",
    "REQUIRED": "要求",
    "THE NOVA CHRYSALIS": "新星蛹",
    "THE PROTOFORM": "原始形态",
    "TITAN": "泰坦",
    "XP to next:": "到下一个的经验值：",
    "Lv": "等级",
    "Accelerated Drift": "加速漂移",
    "Ambidexterity": "双元性",
    "ATP Amplification": "ATP放大",
    "ATP Supercapacitor": "ATP超级电容器",
    "Chronostasis": "时间平衡",
    "Cognitive Streamlining": "认知简化",
    "Echoes of The Fallen": "堕落的回声",
    "Enables Pausing in Combat": "允许在战斗中暂停",
    "Enhanced Coordination": "强化配合",
    "Glycogen Reserves": "糖原储备",
    "Glycolytic Boost": "糖酵解促进",
    "Mito-Crystal Matrix": "线粒体晶体基质",
    "Mito-Torque Induction": "线粒体转矩感应",
    "Mitochondrial Overdrive": "线粒体超速",
    "Mitochondrial Vaults": "线粒体金库",
    "Mutagenic Recall": "诱变的回忆",
    "Nova Genesis Core": "新星成因核心",
    "Optimized Mapping": "优化映射",
    "Option to Mutate is Immediately Available": "突变选项立即可用",
    "Oscillating Biocurrent": "振荡生物电流",
    "Overclocked Respiration": "超频呼吸",
    "Perhaps a tale for another time...?": "也许以后再说吧…？",
    "Primordial Reserves": "原始储备",
    "Reservoir Cells": "储层细胞",
    "RESET Calculations Auto-Include Previously Defeated Enemies": "重置计算自动包括先前击败的敌人",
    "Resonant Cell Array": "共振单元阵列",
    "Stardust Cache": "星尘缓存",
    "Synaptic Reverb": "突触反射",
    "Synaptic Splitstream": "突触分裂流",
    "Tactical Expansion": "战术上的扩张",
    "Voidborne Hypercell": "空洞性超细胞",
    "Begin": "开始",
    "Embers": "余烬",
    "Dissolve into the Astral Cascade, where you may rise anew?": "溶入星体瀑布, 你可以重新崛起吗?",
    "Turn Back": "返回",
    "XP and": "经验值和",
    "You will gain": "你将获得",
    "Cost:": "成本:",
    "Amoeboid Movement": "变形运动",
    "Phagocytosis": "吞噬作用",
    "STR boosts exploration speed by ×1000 while \"Pseudopodia\" is equipped": "力量可以在装备“伪足”的同时提高探索速度×1000",
    "Every equipped UNICELLULAR structure increases BIOMATTER scavenging speed by ×2 (Multiplicative)": "每个装备的单细胞结构增加×2（乘法）收集生物物质的速度",
    "Bolster": "支撑",
    "Bulk Up": "发展壮大",
    "Efficient Metabolism": "高效代谢",
    "Empower": "赋能",
    "For each BIOMATTER scavenged, gain 10× more instead": "每拾取1个生物物质，则获得10倍效果",
    "Grit": "坚韧",
    "Invigorate": "振奋精神",
    "Mettle": "勇气",
    "Bdelloid Rotifer": "蛭形轮虫",
    "Its trophi click, menacing, aggressive.": "它的口器咔咔作响，充满威胁，咄咄逼人。",
    "Numerous cilia spin wildly, propulsion erratic.": "无数纤毛疯狂地旋转，推进力不稳定。",
    "Ciliary Dance": "纤毛之舞",
    "Deal 6 consecutive hits of [0.3×DEX] PHYS damage.": "造成连续6次[0.3×灵巧]的物理伤害。",
    "AGILITY answers.": "敏捷的答案。",
    "BREATHE": "呼吸",
    "Distance, a barrier. But also a question.": "距离，是一种障碍。但同时也是一个问题。",
    "Fleet-footed": "脚步迅捷",
    "How far? How fast?": "有多远？有多快?",
    "The world is vast.": "世界是广阔的。",
    "Unlocks LUNGS.": "解锁肺部。",
    "AGILITY": "敏捷",
    "Combat DEXTERITY": "战斗灵巧",
    "Combat Move Cooldown Speed [via DEXTERITY]": "战斗移动冷却速度[通过灵巧]",
    "Exploration Speed": "探索速度",
    "Misc. Cascade Upgrade Effects": "杂项。级联升级效果",
    "Plasma Membrane": "质膜",
    "...this may take a while.": "…这可能需要一段时间。",
    "A giant creature unbothered;": "不受打扰的巨大生物；",
    "Graze": "放牧",
    "Heal self for [0.1×VIT] per second over 10 seconds.": "每秒治疗自己[0.1×活力]，持续10秒。",
    "in its element, thriving.": "其乐融融，欣欣向荣。",
    "Inconveniently blocks the way forward.": "挡住了前进的路。",
    "Tardigrade": "缓步动物",
    "At edges of thought, unseen shapes flicker.": "在思想的边缘，看不见的身影闪烁。",
    "But, with sufficient CONSTITUTION, brims with POTENTIAL.": "但是，有了足够的体质，就充满了潜力。",
    "Different. Not you. But also you?": "不同。不是你。你也是吗？",
    "ENDURE. EMBRACE.": "忍受。拥抱。",
    "FLESH": "肉体",
    "Foreign Substance": "外来物质",
    "LIMBS": "四肢",
    "STR boosts exploration speed by ×1000 while \"Pseudopodia\" (default starting limbs) is equipped": "当装备了\“伪足”（默认的起始肢体）时，力量通过×1000提升探索速度",
    "The matter shifts. Stabs and stings.": "物质发生了变化。刺伤和蜇伤。",
    "Unlocks LIVER. Unlocks MUTAGEN collection.": "解锁肝脏。解锁诱变剂集合。",
    "Combat AP Regen Rate [via FORTITUDE]": "战斗行动力回复速度[通过 坚韧]",
    "Combat FORTITUDE": "战斗坚韧",
    "CONSTITUTION": "体质",
    "Contractile Vacuole": "收缩液泡",
    "LIVER": "肝脏",
    "LUNGS": "肺",
    "Mutagen Scavenging Speed": "诱变剂收集速度",
    "Import failed, recheck save file!": "导入失败，请重新检查存档文件！",
    "Save import successful!": "存档导入成功！",
    "Continue on. Skips event for remaining run.": "继续前进。跳过剩余运行的事件。",
    "Fresh, cold air. Faint, just past the rubber seams.": "新鲜、寒冷的空气。微弱，刚过橡胶缝。",
    "Requires 5000 CON. Unlocks shortcut.": "需要5000 体质。解锁快捷方式。",
    "Seal": "封印",
    "SECRETE ACID. CORRODE IT.": "酸分泌。腐蚀。",
    "Too small to escape.": "太小了，逃不掉。",
    "A swaying stalk senses disturbances.": "摇曳的茎秆可以感知到干扰。",
    "Apply [0.5×FOR] Poison/sec for 10s.": "施放[0.5×坚韧]毒/秒，持续10秒。",
    "Hydra Vulgaris": "寻常九头蛇",
    "It waits for prey.": "它在等待猎物。",
    "Nematocyst Jab": "刺丝囊注射",
    "Tentacles drift, extending and retracting with precision.": "触手漂移，伸展和收缩精确。",
    "Toxin Dart": "毒素飞镖",
    "Lobopods": "叶足类",
    "Malpighian Tubules": "马氏管",
    "Mesenchyme": "间充质",
    "MULTICELLULAR": "多细胞",
    "Papulae": "丘疹",
    "Accelerated Morphogenesis": "加速形态发生",
    "AEGIS": "圣盾",
    "Every MULTICELLULAR structure increases MUTAGEN scavenging speed by ×1.5 (Multiplicative)": "每一个多细胞结构都增加了×1.5（倍增性）的诱变剂收集速度",
    "Fleetfoot": "快步",
    "For each MUTAGEN scavenged, gain 3× more instead": "每收集一个诱变剂，获得3倍的额外奖励",
    "Fortified": "强化",
    "Kinetic Accrual": "动能累积",
    "METAMORPHOSIS": "蜕变",
    "Quicken": "加速",
    "Reflex": "反射",
    "Resilience": "韧性",
    "Resolute": "坚决",
    "Streamlined Genetics": "流线型基因",
    "THE COMPOSITE": "复合",
    "ZEPHYR": "和风",
    "Total Mutagen Spent": "消耗的诱变剂总量",
    "Deal [0.5×PWR] PHYS damage, 30% chance to apply [0.2×FOR] Poison/sec for 10s": "造成[0.5×能量]物理伤害，有30%几率造成[0.2×坚韧]毒药/秒，持续10秒",
    "Heal self for [2×FOR] health.": "治疗自身[2×坚韧]点生命",
    "Recover": "恢复",
    "Sampling Room": "取样室",
    "Multiply MUTAGEN scavenging speed by ∛(STR) while \"Lobopods\" is equipped": "当装备“叶足类”时，将诱变剂收集速度乘以∛（力量）",
    "[MAX]": "[最大]",
    "[Max:": "[最大:",
    "ABERRANCY": "反常",
    "Activates when stats are 150 or over. VIT: Heal 50% HP. PWR: Apply 1 Exsanguinate. FOR: Apply 1 Corrosion. DEX: Apply 1 stack of [DEX] bleed per sec for 5s. MND: Apply 1 stack of [MND] poison per sec for 5s.": "当属性值超过150时激活。活力：回复50%的生命值。能量：使用1个抽血。用于：施加1点腐蚀效果。灵巧：每秒释放1层灵巧流血，持续5秒。智慧：每秒附加1层[智慧]毒伤，持续5秒。",
    "NO ACTIVE JOBS": "暂无可用工作",
    "EYES": "眼睛",
    "BRAIN": "大脑",
    "CODEX": "法典",
    "Feed": "喂养",
    "Honed In": "锁定目标",
    "Items": "物品",
    "Items:": "物品:",
    "Nucleus": "细胞核",
    "ORACLE": "神谕",
    "Aberrant Mass Scavenging Speed": "异常物质清除速度",
    "Aberrant Momentum": "反常动量",
    "Add 1 stack of ARMOR to self for 20 seconds. Each stack reduces PHYSICAL damage taken by a flat [FOR÷5].": "为自己增加1层护甲，持续20秒。每一层都能减少扁平物受到的物理伤害[坚韧÷5]。",
    "Adrenaline Stimulant": "肾上腺素兴奋剂",
    "Apply 1 stack of PRIMED to self for 5 seconds.": "为自身附加1层PRIMED，持续5秒。",
    "Archive Decryption Speed": "档案破译速度",
    "Bastion": "堡垒",
    "Biofilm Shield": "生物膜护盾",
    "Blinding Wrath": "致盲之怒",
    "Brilliance": "才华横溢",
    "Burning Spirit": "燃烧之灵",
    "Calculate": "计算",
    "Cognitive Bio-Interlink": "认知生物互联",
    "Cognitive Leap": "认知飞跃",
    "Combat ACUMEN": "战斗敏锐度",
    "Combat MIND": "战斗心态",
    "Combat PHYS Crit. Chance [via ACUMEN]": "打击物理暴击。概率[通过敏锐]",
    "Consume": "消耗",
    "Created with Sketch.": "创建草图。",
    "Creatine Powder": "肌酸粉",
    "Curious, glowing thing. Emits a faint buzz.": "奇怪的，发光的东西。发出微弱的嗡嗡声。",
    "Deal [PWR×2] PHYS damage, 50% chance to apply [0.4×FOR] Poison/sec for 10s": "造成[能量×2]物理伤害，50%几率施放[0.4×坚韧]毒药/秒，持续10秒",
    "Deal [PWR×2] PHYS damage, heal self for 50% of damage dealt.": "造成[能量×2]物理伤害，治疗自己50%的伤害",
    "Deal a powerful blow for [3×PWR] PHYS damage.": "造成[3×能量]点物理伤害。",
    "Devour": "吞噬",
    "Energy Drink": "能量饮料",
    "Every 2 CORRUPTED or ELDRITCH structure provides 1 \"Aberrant Regrowth\" buff on combat start": "战斗开始时，每有2个被腐蚀或邪魔的建筑提供1个“异常再生”增益",
    "Every equipped COMPLEX structure increases Item Drop Rate by ×1.25 (Multiplicative)": "每个装备的复杂结构增加物品掉落率×1.25（乘法）",
    "Experimental Treatment": "实验性治疗",
    "Exsanguinating Rake": "放血耙",
    "Eyedrops": "眼药水",
    "Fast Strike": "快速打击",
    "Fine Motor Advantage": "精细运动优势",
    "First Aid": "急救",
    "First Aid Kit": "急救箱",
    "Flowstate": "流动状态",
    "Focus": "专注",
    "focus_center_round [#ffffff]": "focus_center_round [# ffffff]",
    "For each ABERRANT MASS scavenged, gain 2× more instead": "每清除一个异常物质，增加2倍",
    "Forager's Instincts": "觅食本能",
    "Gain ×100 ABBERANT MASS for each ABERRANT MASS scavenged (Multiplicative). While ELDRITCH, ×1.2 to all combat stats": "每清除一个异常物质获得×100异常物质（乘法）。当邪魔时，×1.2所有战斗属性",
    "Gain 2^(Equipped ELDRITCH Structure Count)× ABERRANT MASS for each ABERRANT MASS scavenged (Multiplicative)": "每清除一个异常物质，获得2^（装备邪魔构造计数）×异常物质（乘法）",
    "General Antibiotics": "普通抗生素",
    "Genetic Reverb": "基因混响",
    "Grants access to moves: First Aid, Stimulant Surge": "允许采取措施：急救，兴奋剂激增",
    "Growth Booster": "生长助推器",
    "Handheld Transmitter": "手持发射机",
    "Harden Carapace": "硬化外壳",
    "Heal self for [2×FOR] health, quickly.": "治愈自己[2×坚韧]健康，迅速。",
    "Heal self for [2×MND] health.": "治疗自己获得[2×智慧]生命值。",
    "If user's highest stat is 2x greater than enemy FOR, apply Heal Block to enemy for 15s.": "如果使用者的最高属性是敌人的2倍，对敌人施加治疗格挡，持续15秒。",
    "Increases AGILITY by 5% (additive)": "增加敏捷5%（附加）",
    "Increases base ACUITY by 0.2 (additive)": "提高基础敏锐度0.2（附加）",
    "Increases base DEXTERITY by 0.2 (additive)": "增加基础灵巧0.2(附加)",
    "Increases base FORTITUDE by 0.2 (additive)": "增加基础韧性0.2（附加）",
    "Increases base MIND by 0.2 (additive)": "增加基础智慧0.2（附加）",
    "Increases base POWER by 0.2 (additive)": "增加基础能量0.2（附加）",
    "Increases base VITALITY by 0.2 (additive)": "增加基础活力0.2（附加）",
    "Increases BODY by 5% (additive)": "增加身体5%（添加剂）",
    "Increases CONSTITUTION by 5% (additive)": "增加体质5%（附加）",
    "Increases INTELLIGENCE by 5% (additive)": "增加5%智力（附加）",
    "Increases PERCEPTION by 5% (additive)": "增加5%的感知能力（附加）",
    "Increases STRENGTH by 5% (additive)": "力量增加5%（添加）",
    "Insight": "洞察力",
    "Instant Coffee": "速溶咖啡",
    "INTELLIGENCE": "智力",
    "Iron Gut": "铁肠道",
    "Keen Eye": "敏锐的眼睛",
    "Metabolic Echo": "代谢回声",
    "Multiply ABERRANT MASS scavenging speed by current Cascade level": "将异常物质清除速度乘以当前级联等级",
    "Multiply BIOMATTER scavenging speed by ∛(STR) while \"Human Limbs\" is equipped": "当装备“人类四肢”时，将生物物质清除速度乘以∛（力量）",
    "Multiply BIOMATTER scavenging speed by current Cascade level": "将生物物质清除速度乘以当前级联等级",
    "Multiply Item Drop Rate by log10(STR) while \"Dexterous Forelimbs\" is equipped": "装备“灵巧前肢”时，将物品掉落率乘以log10(力量)",
    "Multiply MUTAGEN scavenging speed by current Cascade level": "将变异原清除速度乘以当前级联等级",
    "Multiply PWR by ×2 while \"Corrupted Claws\" is equipped": "当装备“腐化之爪”时，将能量乘以×2",
    "Myelin Extract": "髓磷脂中提取",
    "Necrotic Bloom": "坏死开花",
    "Oculus Graft": "眼睛移植",
    "PERCEPTION": "感知",
    "Perform a single hit of [DEX + PWR] PHYS damage.": "造成一次[灵巧 + 能量]物理伤害。",
    "Photoreceptors": "感光器",
    "Power Strike": "强力打击",
    "Premonition": "预感",
    "Prime Up": "启动",
    "Pure Power": "纯粹的精神力量",
    "Rabid Bite": "疯狂的咬",
    "Rake the enemy for [2×PWR] PHYS damage and apply 1 stack of Exsanguination for 20 seconds.": "对敌人造成[2×PWR]物理伤害，并施加1层抽血，持续20秒。",
    "Random effect (25% chance ea.): Heal enemy for [0.5×MND], Do nothing, Deal [2×MND] Poison damage, or Apply 3 stacks of Corrosion for 20s.": "随机效果（25%几率）：治疗敌人[0.5×智慧]，不做任何事，造成[2×智慧]毒性伤害，或施加3层腐蚀效果，持续20秒。",
    "Rapid Recovery": "快速复苏",
    "Recover [0.5×MND] AP.": "恢复[0.5×智慧] AP。",
    "Regen Serum": "回复血清",
    "Relic Runner": "遗物跑者",
    "Removes all current debuffs on self.": "移除所有当前对自我的减益。",
    "Renew": "续订",
    "Restores an additional 0.5% of Max Health per second when out of combat": "当脱离战斗状态时，每秒额外恢复0.5%的最大生命值",
    "Scavenger's Bounty": "拾荒者的恩赐",
    "Scavenging Item Drop Rate": "清除物品掉落率",
    "Special Event skill. Every HUMAN structure increases archive decoding speed by 1.5 (Multiplicative)": "特殊事件技能。每一个人类结构将存档解码速度提高1.5（乘法）",
    "Specialist Strike": "专家罢工",
    "Specimen Storage": "样品存储",
    "Stem Cell Cluster": "干细胞群",
    "Stimulant Surge": "兴奋剂飙升",
    "Suppression": "抑制",
    "Synapse Accelerator": "突触加速器",
    "THE FORSAKEN": "被遗忘者",
    "THE UNFATHOMABLE": "深不可测",
    "THE VOYAGER": "航海家",
    "THE WAYFARER": "旅人",
    "Theorycraft": "理论工艺",
    "Twice-Bled Harvest": "两次流血的收获",
    "Unchecked Expansion": "无节制的扩张",
    "Uniques": "独特",
    "Unlocked Archives": "解锁档案",
    "Untapped Potential": "未开发的潜力",
    "Vampiric Siphon": "吸血鬼虹吸",
    "While COMPLEX, multiply AGILITY by Inventory Item Count and DEXTERITY by log10(Inventory Item Count). Begin combat with 3 stacks of Evade": "当复杂时，敏捷乘以库存物品数量，敏捷乘以log10（库存物品数量）。以3层躲避开始战斗",
    "While Eldritch, Gain ×10 ABERRANT MASS for each ABERRANT MASS scavenged (Multiplicative)": "当邪术时，每清除一个异常物质就获得×10异常物质（乘法）",
    "While HUMAN: ×10 INTELLIGENCE and ×3 MIND. Gain ×3 Exploration speed via speedwalking.": "当人类：×10智力和×3智慧。通过竞走获得×3探索速度",
    "While MULTICELLULAR, multiply all base stats by held mutagen and increase base FORTITUDE by √(Held Mutagen)": "当多细胞时，所有基础属性乘以持有的变异原，并增加基础坚韧√（持有变异原）",
    "While UNICELLULAR: ×2 BODY and +10 base VITALITY per Endoplasm level. BODY affects movement speed": "而单细胞：×2身体和+10基础活力每内质等级。身体影响移动速度",
    "Central Nervous System": "中枢神经系统",
    "COMPLEX": "复合体",
    "Compound Eyes": "复眼",
    "Connective Tissue": "结缔组织",
    "Dexterous Forelimbs": "灵巧的前肢",
    "Hepatopancreas": "肝胰腺",
    "Tracheal System": "气管系统",
    "A nearby terminal blinks with glowing bold text.": "附近的一个终端闪烁着发光的粗体文字。",
    "Access Lock": "访问锁",
    "an escape hatch is nestled in a far wall.": "一个逃生舱口坐落在远处的墙上。",
    "Behind rows upon rows of specimens,": "在一排排的标本后面，",
    "EMERGENCY PROTOCOL ACTIVE — ACCESS RESTRICTED": "紧急协议已激活，限制访问",
    "Human Eyes": "人类的眼睛",
    "Human Liver": "人类的肝脏",
    "Human Lungs": "人类的肺",
    "Human Muscle": "人类肌肉",
    "It won't budge.": "它不会动。",
    "PERFORM MANUAL OVERRIDE": "手动覆盖",
    "Requires 500M INT. Unlocks shortcut.": "需要500M 智力。解锁快捷方式。",
    "Total Aberrant Mass Spent": "消耗的总异常物质",
    "Adaptive Mutation": "自适应变异",
    "Begin discovering your roots.": "开始寻找你的根。",
    "Bloodwork": "血检",
    "Breaking Point": "断点",
    "Cogito, Ergo Sum": "我思故我在",
    "Cold Archive": "冷档案",
    "Defeat the First Enemy in Area 4.": "在第4区击败第一个敌人",
    "Defeat the First Enemy in Area 5.": "在第5区击败第一个敌人",
    "Defeat the Second Enemy in Area 4.": "在第4区击败第二个敌人",
    "Defeat the Second Enemy in Area 5.": "在5区击败第二个敌人",
    "Defeat the Third Enemy in Area 4.": "在第4区击败第三个敌人",
    "Defeat the Third Enemy in Area 5 (for Real).": "在第5区击败第三个敌人",
    "Echoes Beneath": "地下回响",
    "Failsafe Offline": "故障安全离线",
    "Grants access to move: Resonance Blast": "授予移动的权限：共振爆炸",
    "Grants access to moves: Quick Shot, Precise Shot": "授予移动权限：快速射击，精确射击",
    "Heat and Humidity": "热和湿度",
    "Permanently Unlock Area 2.": "永久解锁区域2",
    "Permanently Unlock Area 3.": "永久解锁区域3",
    "Permanently Unlock Area 4.": "永久解锁第4区",
    "Permanently Unlock Area 5.": "永久解锁第5区",
    "Permanently Unlock Area 6.": "永久解锁6区",
    "Resonance Blaster": "共振爆破器",
    "Sampling Protocol": "抽样协议",
    "Standard Issue Firearm": "标准配发火器",
    "TASKS": "任务",
    "Theories Unbound": "未绑定理论",
    "Undead Regeneration": "亡灵再生",
    "Voidwalker": "虚空行者",
    "Research Wing": "研究部门",
    "Underground Facility": "地下设施",
    "Endings Seen": "看到的结局",
    "Assimilate": "同化",
    "Deal [10×(SELF VIT - TARGET FOR)] PHYS damage.": "造成[10x（自身 活力 - 目标坚韧）]的物理伤害。",
    "A perfect blueprint for mimicry. [Lost on Reset]": "一个完美的模仿的蓝图。[迷失在重置中]",
    "Bloodstained ID Card": "血迹斑斑的身份证",
    "Corrupted Flesh": "腐化的肉体",
    "Corrupted Gaze": "腐化的目光",
    "Corrupted Mind": "腐化的心灵",
    "Corrupted Thorax": "腐化的胸腔",
    "Corrupted Viscera": "腐化的脏腑",
    "ELDRITCH": "邪魔",
    "Writhing Manifestations": "扭动的表现",
    "Neural Mesh": "神经网格",
    "Ocelli": "单眼",
    "Horizon Engulfed by Advancing Mass": "地平线被前进的物质吞没",
    "Authorities have confirmed the emergence of a massive, unidentified biological entity from the Eldrite Core disaster site. The mass, described as a shifting, semi-translucent membrane, continues to grow at an exponential rate, absorbing soil, vegetation, wildlife, and structures alike.": "当局已经确认在爱尔德雷德核灾难现场出现了一个巨大的，身份不明的生物实体。这个体量被描述为一个移动的半透明膜，以指数速度持续增长，吸收土壤、植被、野生动物和建筑等。",
    "Attempts at containment have failed; conventional weaponry appears ineffective against its constant regeneration. Satellite imaging shows the vast, writhing front stretching over thirty miles, advancing steadily toward urban sectors.": "遏制的尝试已经失败；常规武器似乎对它的不断再生无效。卫星图像显示，巨大的、扭曲的锋面绵延30英里，稳步向城市地区推进。",
    "Evacuation of surrounding towns is underway, but officials warn that the expansion rate is outpacing current efforts. Citizens are urged to remain calm, follow evacuation directives, and avoid any direct contact with the entity at all costs.": "周边城镇的疏散工作正在进行，但官员们警告说，扩张速度超过了目前的努力。敦促市民保持冷静，遵循疏散指令，不惜一切代价避免与实体直接接触。",
    "Updates will continue until communications are severed.": "通讯中断前将继续更新。",
    "Parasitic Outbreak Linked to Contaminated Meat": "受污染肉类导致寄生虫爆发",
    "The Department of Public Health has issued a nationwide recall following reports of severe illness linked to contaminated livestock and seafood. Symptoms include extreme fatigue, muscle degradation, and neurological impairment. Preliminary investigation points to an unidentified parasitic organism, resistant to conventional sterilization and antibiotic protocols.": "在有报告称受污染的牲畜和海鲜导致严重疾病后，公共卫生部发布了全国范围的召回。症状包括极度疲劳、肌肉退化和神经损伤。初步调查表明是一种未知的寄生生物，对传统的消毒和抗生素方案有抗药性。",
    "Authorities are investigating potential links to the Solstice Industries R&D facility. Meanwhile, citizens are urged to avoid all unprocessed animal products until further notice.": "当局正在调查与夏至工业研发中心的潜在联系。同时，在进一步通知之前，市民应避免食用所有未经加工的动物产品。",
    "Further advisories pending.": "有待进一步咨询。",
    "Unidentified Hostile Creature Prompts State of Emergency": "不明敌对生物引发紧急状态",
    "Panic is mounting across several districts following a series of brutal attacks by an unidentified creature over the past 48 hours. Witnesses describe a massive, quadrupedal entity exhibiting extreme strength and speed. Initial reports were dismissed as hoaxes by local wildlife agencies; however, an armed response team dispatched to investigate has since disappeared without trace.": "在过去的48小时内，一个不明生物对几个地区进行了一系列残酷的袭击，恐慌情绪正在蔓延。目击者描述了一个巨大的四足生物，表现出极大的力量和速度。最初的报道被当地野生动物机构斥为骗局；然而，一支被派去调查的武装反应小组从此消失得无影无踪。",
    "Authorities have detained an unidentified individual seen emerging from the site of the recent Eldrite Core disaster. Sources believe they are the sole survivor of the catastrophe, though officials have yet to comment on whether they pose a biological risk. Solstice Industries HQ has remained silent, issuing only a brief statement:": "当局拘留了一名身份不明的人，有人看到他出现在最近的爱尔德雷特核灾难现场。消息人士认为，他们是这场灾难的唯一幸存者，尽管官员们尚未就他们是否构成生物风险发表评论。至日工业总部一直保持沉默，只发布了一份简短声明：",
    "Attempts to contain the entity upon their emergence were met with catastrophic failure—an elite containment squad engaged but was swiftly and brutally dispatched. Forensic analysis confirms remains of the personnel have been partially consumed. Further reports indicate a trail of similarly mutilated bodies leading from the facility toward populated areas.": "试图在它们出现时遏制它们的努力遭遇了灾难性的失败——一支精英遏制小组参与了进来，但被迅速而残酷地遣散了。法医分析证实部分遇难者遗体已被吞噬。进一步的报告显示，类似的残缺不全的尸体从该设施通往人口稠密地区。",
    "Most people just call it “The Bloom.” Solstice says it’s helping stabilize radiation levels around the Core. Not just containing — actively reducing. The official line is: “uncertain mechanism of remediation.” But Daniel says it’s eating the fallout. Slowly. Constantly.": "大多数人都叫它“花开”夏至号说它在帮助稳定地核周围的辐射水平。不只是含有，而是主动还原。官方的说法是：“不确定的补救机制。”但丹尼尔说它正在吞噬辐射尘。缓慢。不断。",
    "At ground level, surrounding terrain has begun to deform. Hills, treelines, and manmade structures within a 12-kilometer radius appear to be warping upward, pulled incrementally toward the central tower.": "在地面上，周围的地形已经开始变形。半径12公里内的山丘、林木线和人造建筑似乎都在向上弯曲，逐渐被拉向中央塔。",
    "Its ascent has begun to curve, tilting unnaturally toward solar alignment. Aerospace analysts note that the structure should have collapsed under its own mass under current gravitational loads. However, telemetry suggests the presence of internal counterforces, possibly biomechanical in origin, actively stabilizing the ascent.": "它的上升已经开始弯曲，不自然地向太阳的方向倾斜。航空分析人士指出，在目前的重力载荷下，该结构应该是在自身质量的作用下坍塌的。然而，遥测显示存在内部反作用力，可能源于生物力学，积极稳定上升。",
    "Lily tried to draw it from memory. It took up the whole page — just layer after layer of rainbow-colored curves. She gave it a smile, even though Daniel says it doesn’t really have a face. Asked if it could wave. “It’s learning to,” Daniel said.": "莉莉试着从记忆中画出来。它占据了整个页面——一层又一层彩虹色的曲线。她对它笑了笑，尽管丹尼尔说它其实没有脸。问它能不能挥手。“这是在学习，”丹尼尔说。",
    ", thinks most of us carry it now. A quiet mutualism. Barely more than a few cells. But when something’s wrong — an infection, a fever — it reacts. It’s strange. I haven’t had a migraine in weeks. The ache in my knees? Gone. Lily caught a cold last week, and it cleared up in two hours. No more night terrors, either.": "，认为我们大多数人现在都带着它。一种安静的互惠主义。只有几个细胞。但当出现问题时，比如感染、发烧，它就会做出反应。这是奇怪的。我好几周没偏头痛了。膝盖疼吗？一去不复返了。莉莉上周感冒了，两小时后就好了。也不会再有夜惊了。",
    "Solstice tried running the whole containment protocol suite. Enclosure. Sedatives. But it always broke out. Didn’t attack. Didn’t lash out. Just circled back here, repeatedly. Waited on the porch. One time, Daniel opened the door and it just… stepped in. Like it remembered where it was welcome.": "夏至试过运行整个隔离协议套件。外壳。镇静剂。但它总是爆发。没有攻击。没有大发脾气。只是绕回来了，反复地。在门廊上等着。有一次，丹尼尔打开门，它就进来了。好像它还记得在哪里欢迎它一样。",
    "Lily took to it immediately. She calls it “Novie,” and it doesn’t seem to mind. Feeds it bits of toast in the morning. Likes to cuddle with it by the fire. It’s big — really big — but gentle. Sleeps at the foot of her bed like a dog. Always between her and the door.": "莉莉马上就喜欢上了。她叫它“诺维”，它似乎并不介意。早上喂它一点面包片。喜欢在火炉边抱着它。它很大——很大——但是很温柔。像狗一样睡在她的床脚。总是在她和门之间。",
    "Solstice still checks in. Monthly visits. Scans. Logs. But they’ve stopped pushing for relocation. It doesn’t respond to anyone else. Prefers our living room rug and the sun through the east window.": "夏至还会来报到。每月的访问。扫描。日志。但他们已经停止推动搬迁。它对其他任何人都没有反应。更喜欢客厅的地毯和从东窗透进来的阳光。",
    "They’re quiet. Hardly a word spoken since they arrived, but somehow they always know what needs doing. Dishes, laundry, little repairs around the house. The kind of chores that pile up without you noticing — only now they don’t. The curtain rod’s fixed. The fridge hums quieter. The heater doesn’t rattle anymore.": "他们安静。他们来了之后几乎没说过一句话，但不知怎么的，他们总是知道该做什么。洗碗，洗衣服，房子周围的小修理。这种琐事会在你没有注意到的情况下堆积起来——只是现在它们没有了。窗帘杆固定好了。冰箱的嗡嗡声更小了。加热器不响了。",
    "The first time Daniel asked if I wanted to have dinner again — just the two of us — I nearly cried. It’s been years since we had time. Real time. No rushing. No reports waiting. Just space for us to be people again. A couple again.": "丹尼尔第一次问我是否想再一起吃晚饭——就我们两个——我差点哭了。我们已经好多年没有时间了。真正的时间。没有匆忙。没有报告等待。只是给我们做回普通人的空间。又是一对。",
    "He fixed the front door lock on day one. Said it was too loud. Reorganized the kitchen drawers, one by one. Spent hours sharpening the old knives in silence. He asked about the neighbors. Their schedules. Who lives alone.": "他第一天就把前门的锁修好了。说声音太大了。重新整理了厨房的抽屉，一个接一个。花了几个小时默默地磨旧刀。他询问邻居的情况。他们的时间表。一个人住。",
    "I told myself it was trauma, some need to control his environment. But then I saw him in the backyard, digging near the compost bin. When I asked, he said he was “making space.” I asked about Mrs. Kellis next door. He said she moved. But her car’s still there.": "我告诉自己这是心理创伤，有些人需要控制自己的环境。但后来我看到他在后院，在堆肥箱附近挖土。当我问他时，他说他在“腾出空间”。我问起了隔壁的凯利斯太太。他说她搬家了。但她的车还在那儿。",
    "In response, officials have imposed dusk-to-dawn curfews across affected regions. Military assistance has been formally requested but remains under review.": "作为回应，官员们在受影响地区实施了从黄昏到黎明的宵禁。军事援助已正式提出请求，但仍在审查中。",
    "Further updates forthcoming.": "进一步的更新即将到来。",
    "Sole Survivor of Eldrite Core Disaster Detained": "艾德瑞特核心灾难的唯一幸存者被拘留",
    "\"The situation is under control. There is no cause for public concern.\"": "“局势已经得到控制。公众没有理由担心。”",
    "Developing story—updates to follow.": "开发后续的故事更新。",
    "Is there a better end? [New Run]": "有更好的结局吗？(新运行)",
    "Brutal Killer-Cannibal on the Loose": "野蛮的食人杀手在逃",
    "Authorities have issued a citywide alert following the escape of a highly dangerous individual from the Solstice Industries R&D Facility.": "当局已经发布全市警报因为一名非常危险的人从夏至工业研发中心逃走了。",
    "Officials have yet to disclose the full extent of the threat but urge the public to remain indoors, lock all entry points, and report any sightings immediately.": "官员们尚未公布威胁的全部程度，但敦促公众留在室内，锁定所有入口，并立即报告任何目击事件。",
    "Updates will follow as the situation develops.": "随着情况的发展，我们会跟进最新消息。",
    "Anomalous Spire Extends Skyward": "反常尖塔向天空延伸",
    "Officials have confirmed that the structure emerging from the Solstice Core site has breached the upper atmospheric threshold.": "官员们已经证实，从冬至核心地点出现的结构已经突破了大气上限。",
    "The growth, now over 70 kilometers in height, exhibits behavior inconsistent with known biological or geological processes.": "这种生长物现在高度超过70公里，表现出与已知的生物或地质过程不一致的行为。",
    "Traffic data shows major congestion along Interstate 17 and Route 84 as evacuation continues. Estimated delays exceed thirteen hours, with some vehicles abandoning roadways altogether.": "交通数据显示17号州际公路和84号公路严重拥堵，疏散工作仍在继续。预计延误时间超过13个小时，一些车辆完全弃路。",
    "Further updates as permitted by signal stability.": "根据信号稳定性进一步更新。",
    "Bigger Than the Page": "比页面更大",
    "Daniel’s been doing interviews again. He always gets quiet afterward — hates the attention, even if most of it's positive now.": "丹尼尔又开始接受采访了。之后他总是很安静——讨厌别人的关注，即使现在大部分的关注都是积极的。",
    "I asked if it’s safe. He said it never once tried to hurt him. Sometimes, on the ridge, you can see the shimmer of it against the horizon. Like oil on water, but breathing.": "我问它是否安全。他说它从来没有试图伤害过他。有时，在山脊上，你可以看到它在地平线上的微光。就像水上的油，但呼吸。",
    "Somehow, I think he means it.": "不知怎么的，我觉得他是认真的。",
    "Carriers": "航空公司",
    "Daniel says most of us carry it now.": "丹尼尔说现在我们大多数人都带着它。",
    "“It’s not dangerous,” he says, over coffee. “Think of it like an immune partner.”": "“这并不危险，”他边喝咖啡边说。“把它想象成一个免疫的伴侣。”",
    "He says they’ve traced the vector: environmental, airborne, likely originated near the breach. It’s not invasive. Not detectable under lab conditions. But it’s there. And it helps.": "他说他们已经追踪到传染源了环境，空气传播，很可能起源于缺口附近。这不是侵入性的。在实验室条件下检测不到。但它就在那里。这很有帮助。",
    "He calls it ": "他称之为",
    "Nova": "新星",
    "Solstice is furious they can’t isolate it in a lab. Can’t monetize it. They’re not thrilled.": "夏至很生气他们不能在实验室里分离它。不能将其货币化。他们并不兴奋。",
    "Maybe it really is just placebo. Maybe we’re just lucky. But I see the way Lily sleeps now — peaceful, still — and I think:": "也许它真的只是安慰剂。也许我们只是幸运而已。但我看到莉莉现在睡觉的样子——安详、安静——我想：",
    "Whatever it is, it wants us to be okay.": "不管它是什么，它希望我们没事。",
    "Creature Comforts": "物质享受",
    "It came back on its own. Tracked through miles of broken forest to find us again.": "它自己回来了。穿过数英里的破碎森林来找我们。",
    "I’ve started buying treats in bulk. Solstice still calls it an anomaly. A risk factor. But I think they’ve realized it’s not leaving — and neither are we.": "我开始大量购买零食了。夏至号仍然称其为异常现象。一个风险因素。但我想他们已经意识到它不会离开——我们也不会。",
    "Caretaker": "看守",
    "Daniel introduced them as Novelle. Said they met during the breach, helped each other survive. They moved in last week. Just until things settle, he told me. I didn’t mind.": "丹尼尔介绍他们为诺维尔。说他们是在入侵期间认识的，互相帮助度过了难关。他们上周搬进来的。他告诉我，等事情解决了再说。我不介意。",
    "Lily adores them. I don’t know why, but I trust her instincts. She says Novelle listens. Knows when she needs her blanket. When she’s hungry. When she just wants to sit quietly and draw.": "莉莉很喜欢。我不知道为什么，但我相信她的直觉。她说诺维尔会倾听。知道自己什么时候需要毯子。当她饿的时候。当她只想静静地坐着画画的时候。",
    "Daniel got them a job at another Solstice facility. Something light. Logistics, mostly. Paperwork. And on the nights we go out, they help watch Lily.": "丹尼尔给他们在另一家夏至工厂找了份工作。光的东西。物流,主要是。文书工作。我们出去的晚上，他们帮忙照看莉莉。",
    "That part’s new. The going out.": "这部分是新的。外出。",
    "I asked Daniel once if he really knew them.": "我曾经问过丹尼尔他是否真的认识他们。",
    "He smiled. “They saved my life,” he said. “That’s enough.”": "他笑了。“他们救了我的命，”他说。“这就够了。”",
    "Not Him": "不是他",
    "He came back.": "他回来了。",
    "No warning. Just standing on the porch one night, like he’d never left. He said he’d escaped during the breach. Hid in the sublevels. Lived off rations.": "没有警告。只是某天晚上站在门廊上，好像他从未离开过。他说他在入侵时逃走了。藏在子层里。靠口粮过活。",
    "He looks like Daniel. Wears his clothes. Moves the way he did. Says the right things, mostly. But he’s not tired. Not gaunt. No scars. No weight lost.": "他看起来像丹尼尔。穿他的衣服。像他那样移动。说的都是对的。但他不累。不憔悴。没有疤痕。体重没有减轻。",
    "I checked the backyard again this morning. There’s a fresh patch of turned soil near the old trellis. And this evening? I found Lily’s shoes by the door. Muddy. Too muddy for a dry day.": "今天早上我又检查了后院。旧棚架附近有一块新翻过的土。今晚呢？我在门边发现了莉莉的鞋子。泥泞。太泥泞了，不适合干的日子。",
    "When I asked, she said Daddy took her out to “look at where the ground is soft.”": "当我问她时，她说爸爸带她出去“看看哪里的地面比较软”。",
    "I told her to stay inside from now on. She didn’t ask why.": "我让她从现在开始待在家里。她没有问为什么。",
    "I think she knows too.": "我想她也知道。",
    "Another Dusk Awaits [New Run]": "另一个黄昏等待[新跑]",
    "STATUS: GLOBAL SYSTEMS OFFLINE": "状态：全局系统脱机",
    "REBUILD. REPEAT. RUIN.": "重建。重复。毁灭。",
    "This automated transmission is to inform surviving recipients that centralized command has ceased operation.": "这种自动传输是为了通知幸存的接收者中央指挥已经停止运作。",
    "Global communication systems have failed.": "全球通信系统已经失灵。",
    "Civil, military, and corporate infrastructures are non-operational.": "民用、军事和企业的基础设施都无法运行。",
    "Hostile biological and existential threats render further survival efforts untenable.": "敌对的生物和生存威胁使进一步的生存努力难以为继。",
    "Final advisories: Remain indoors, conserve all remaining supplies, minimize exposure to external phenomena.": "最后的建议：待在室内，保存所有剩余的物资，尽量减少与外部现象的接触。",
    "No assistance is forthcoming. May the sun guide you.": "没有援助即将到来。愿阳光指引你。",
    "ANTHROPOID": "类人猿",
    "DECRYPT": "解密",
    "DECRYPTING": "解密中",
    "Human Limbs": "人体四肢",
    "LOCKED": "未解锁",
    "Next File ETA:": "下一个文件预计时间：",
    "BREAKING NEWS": "突发新闻",
    "Deal [10×MND] PURE damage to CORRUPTED and ELDRITCH enemies. Fails if user has <1000 MND or has been corrupted.": "对腐化和邪魔血统的敌人造成[10×智慧]纯粹伤害。如果用户 <1000 智慧 或已损坏，则失败。",
    "Deal a flat 300 PHYS damage. [ACU/2]% chance to deal double damage. Fails if user has <100 MND.": "造成300点物理伤害。[精准/2]%几率造成双倍伤害如果用户 <100 智慧 则失败。",
    "Deal a flat 300 PHYS damage. Fails if user has <100 MND.": "造成300点物理伤害。如果用户 <100 智慧 则失败。",
    "Precise Shot": "精准射击",
    "Quick Shot": "快速射击",
    "Resonant Blast": "共振爆炸",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "AP Cost:": "AP成本:",
    "Max AP:": "AP上限:",
    "Max HP:": "生命值上限:",
    "VIT": "活力",
    "PWR": "能量",
    "MND": "心灵",
    "HP:": "生命值:",
    "FOR": "坚韧",
    "AP:": "AP:",
    "ACU": "精准",
    "DEX": "灵巧",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "s": "",
    "×": "×",
    "|": "|",
    "/": "/",
    "—": "—",
    ":": ":",
    "!!": "!!",
    "(": "(",
    ")": ")",
    "[": "[",
    "]": "]",
    "%)": "%)",
    ".cls-1{fill:none;stroke:#ffffff;stroke-miterlimit:10;stroke-width:1.91px;}": ".cls-1{fill:none;stroke:#ffffff;stroke-miterlimit:10;stroke-width:1.91px;}",
    "•": "•",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高物质树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "You are": "你是",
    "New Area Unlocked: ": "新区域已解锁：",
    "target [#": "目标 [#",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+) AM$/,
    /^([\d\.]+):([\d\.]+) PM$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+) m$/,
    /^([\d\.]+) m³$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+)TASKS(.+)$/, '$1任务$2'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^×([\d\.]+) DEXTERITY$/, 'x$1 灵巧'],
    [/^×([\d\.]+) FORTITUDE$/, 'x$1 坚韧'],
    [/^×([\d\.]+) CONSTITUTION$/, 'x$1 体质'],
    [/^×([\d\.]+) AGILITY$/, 'x$1 敏捷'],
    [/^×([\d\.]+) ACUITY$/, 'x$1 敏锐'],
    [/^×([\d\.]+) MIND$/, 'x$1 智慧'],
    [/^×([\d\.]+) PERCEPTION$/, 'x$1 感知'],
    [/^×([\d\.]+) INTELLIGENCE$/, 'x$1 智力'],
    [/^×([\d\.]+) STRENGTH$/, 'x$1 力量'],
    [/^×([\d\.]+) POWER while in CORRUPTED stage$/, 'x$1 能量当在腐化关卡'],
    [/^×([\d\.]+) STRENGTH, ×([\d\.]+) POWER$/, 'x$1 力量，x$2 能量'],
    [/^×([\d\.]+) PERCEPTION, ×([\d\.]+) ACUITY$/, 'x$1 感知，x$2 敏锐'],
    [/^×([\d\.]+) BODY, ×([\d\.]+) VITALITY$/, 'x$1 身体，x$2 活力'],
    [/^×([\d\.]+) AGILITY, ×([\d\.]+) DEXTERITY$/, 'x$1 敏捷，x$2 灵巧'],
    [/^×([\d\.]+) CONSTITUTION, ×([\d\.]+) FORTITUDE$/, 'x$1 体质，x$2 坚韧'],
    [/^×([\d\.]+) INTELLIGENCE, ×([\d\.]+) MIND$/, 'x$1 智力，x$2 智慧'],
    [/^x([\d\.]+) STRENGTH$/, 'x$1 力量'],
    [/^×([\d\.]+) POWER$/, 'x$1 能量'],
    [/^x([\d\.]+) POWER$/, 'x$1 能量'],
    [/^×([\d\.]+) BODY$/, 'x$1 身体'],
    [/^x([\d\.]+) BODY$/, 'x$1 身体'],
    [/^×([\d\.]+) VITALITY$/, 'x$1 活力'],
    [/^x([\d\.]+) VITALITY$/, 'x$1 活力'],
    [/^\+([\d\.]+) Base MIND$/, '\+$1 基础智慧'],
    [/^\+([\d\.]+) Base ACUITY$/, '\+$1 基础敏锐'],
    [/^\+([\d\.]+) Base FORTITUDE$/, '\+$1 基础坚韧'],
    [/^\+([\d\.]+) Base DEXTERITY$/, '\+$1 基础灵巧'],
    [/^\+([\d\.]+) Base AP Regen per Second$/, '\+$1 基础AP回复每秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) AP$/, '$1 AP'],
    [/^\+([\d\.,]+) Base POWER$/, '\+$1 基础能量'],
    [/^\+([\d\.,]+) Base VITALITY$/, '\+$1 基础活力'],
    [/^\+([\d\.,]+) Max AP$/, '\+$1 AP上限'],
    [/^\+([\d\.,]+) starting BIOMATTER$/, '\+$1 初始生物物质'],
    [/^\+([\d\.,]+) starting MUTAGEN$/, '\+$1 初始诱变剂'],
    [/^\+([\d\.,]+) ASTRAL EMBERS$/, '\+$1 星体余烬'],
    [/^\+([\d\.,]+) Moveset Slot$/, '\+$1 招式槽位'],
    [/^([\d\.,]+) cm³$/, '$1 cm³'],
    [/^([\d\.,]+)s ago$/, '$1 秒前'],
    [/^([\d\.,]+)m ([\d\.,]+)s ago$/, '$1 分 $2 秒前'],
    [/^Defeat ([\d\.,]+) enemies$/, '击败 $1 敌人'],
    [/^Escape Area ([\d\.,]+)$/, '逃离区域 $1'],
    [/^Spend (.+) Biomatter in Total$/, '总共花费 $1 生物物质'],
    [/^Spend (.+) Mutagen in Total$/, '总共花费 $1 诱变剂'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);