/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Agar Culture": "琼脂培养",
    "Explore": "探索",
    "Archives": "档案",
    "Progress:": "进度:",
    "Save Game": "保存游戏",
    "Just Now": "就是现在",
    "Last Saved:": "最近保存:",
    "SAVES": "保存",
    "Import Game": "导入存档",
    "Export Game": "导出存档",
    "ASSETS": "资源",
    "Off": "关",
    "On": "开",
    "sec.": "秒.",
    "SETTINGS": "设置",
    "Display Format": "显示格式",
    "ABOUT": "关于",
    "All images in the game are hand-drawn, hand-edited, or obtained from open-source image sites. Credits go to: Pexels, Unsplash, Pixabay, Rawpixel, Wikimedia Commons, SVGRepo, iNaturalist, PickPik, Picryl, publicdomainpictures.net, freeimages.com, Font Awesome, Game-icons.net, and CC0 Research Journals.": "游戏中的所有图像都是手绘的，手工编辑的，或者从开源图像网站获得的。感谢：Pexels， Unsplash, Pixabay, Rawpixel, Wikimedia Commons, SVGRepo, iNaturalist, PickPik, Picryl, publicdomainpictures, freeimages.com, Font Awesome, Game-icons.net和CC0 Research Journals。",
    "BIOTOMATA is a semi-active, story-based incremental game, written and made over the last several months for my Final Year Project. It's been a really fun learning process, and I hope you'll have just as much fun playing the game as I did making it!": "《BIOTOMATA》是一款半活跃的基于故事的增量游戏，是我在过去几个月为最后一年的项目编写和制作的。这是一个非常有趣的学习过程，我希望你在玩游戏时也能像我制作游戏时一样开心！",
    "Autosave Interval (s)": "自动保存间隔（秒）",
    "Disable for better performance": "禁用以获得更好的性能",
    "Double Click to Mutate": "双击可进行变异",
    "Endings Found": "发现的结局",
    "Exploration Image Filters": "探索图像滤波器",
    "Hi, welcome to the about screen! This is where I ramble a little about the game :D": "嗨，欢迎来到关于页面！下面是我对游戏的一些介绍",
    "INFO": "信息",
    "May help prevent misclicks": "可能有助于防止误点击",
    "Mom and Dad <3": "妈妈和爸爸<3",
    "My Uni faculty, for letting em build this game for my FYP": "我的大学老师们，让他们为我的五年计划制作这款游戏",
    "Render Dynamic Stars": "渲染动态星星",
    "Set to '0' for 'Never'": "设置为“0”表示“从不”",
    "SPECIAL THANKS": "特别感谢",
    "Time Format": "时间格式",
    "Time in Run": "运行时间",
    "Total Biomatter Spent": "总生物物质消耗",
    "Total Enemies Defeated": "击败敌人总数",
    "Unique Enemies Defeated": "打败的独特敌人",
    "YOU, for helping me playtest the game before official launch!": "感谢你在正式发布前帮助我测试游戏！",
    "Exploring...": "探索中...",
    "Blocker Type:": "拦截器类型:",
    "COMBAT": "战斗",
    "ERROR": "错误",
    "Resolve": "解决",
    "OBSTACLE DETECTED": "检测到障碍物",
    "A wriggling mass. Blocks path forward. Easy to defeat.": "一团蠕动的东西。阻挡前进的道路。很容易被打败。",
    "FIGHT": "战斗",
    "PREPARE": "准备",
    "Simple Bacterium": "简单的细菌",
    "Initiates combat.": "发起战斗。",
    "Feeble Hit": "微弱的打击",
    "NO STATUS ANOMALIES": "暂无异常状态",
    "Basic Attack": "基础攻击",
    "Deal a weak blow of [0.5×PWR] PHYS damage.": "造成[0.5×能量]微弱的物理伤害。",
    "Perform a basic attack for [1×PWR] PHYS damage.": "执行一个基本的[1×能量]物理伤害攻击。",
    "EVENT": "事件",
    "\"Novelle\"": "\“中篇小说\”",
    "A Lil' Twist in the Helix": "螺旋里的小螺旋",
    "Apex Anomaly": "顶点异常",
    "Bad Meat": "坏肉",
    "Bigger than the Page": "比页面更大",
    "Biohacking 101": "生物黑客101",
    "Complete a run as the 1st Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第一个突变阶段的任务",
    "Complete a run as the 1st Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下完成第一个突变阶段的任务",
    "Complete a run as the 2nd Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第2个突变阶段的任务",
    "Complete a run as the 2nd Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下，完成第二个突变阶段的任务",
    "Complete a run as the 3rd Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第三个突变阶段的任务",
    "Complete a run as the 3rd Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下完成第三个突变阶段的任务",
    "Complete a run as the 4th Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第4个突变阶段的任务",
    "Complete a run as the 4th Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下，完成第4个突变阶段的任务",
    "Complete a run as the 5th Mutation Stage after resolving the \"Safe Room\" Event": "在解决“安全房间”事件后完成第五次变异阶段的任务",
    "Complete a run as the 5th Mutation Stage without resolving the \"Safe Room\" Event": "在没有解决“安全房间”事件的情况下完成第五次变异阶段的任务",
    "Complete a run as the 6th Mutation Stage after fully mutating all parts": "在第6个变种阶段中完成所有变种",
    "Complete a run as the 6th Mutation Stage without fully mutating all parts": "在没有完全变异所有部件的情况下完成第六次变异阶段",
    "Creature Comforts": "物质享受",
    "Critical Biomass": "关键的生物量",
    "Defeat your first enemy": "打败你的第一个敌人",
    "Digesting the Data": "消化数据",
    "EVENT": "事件",
    "Evolutionary Arms Race (And You Have Many)": "进化军备竞赛（你有很多）",
    "Extinction Event": "灭绝事件",
    "From Slime to Sublime": "从粘液到崇高",
    "Goo-d for Growth": "促进增长",
    "Grown Beyond Containment": "超出控制范围",
    "Hungry Hungry Nova": "饥饿的新星",
    "Imposter Syndrome": "冒名顶替者综合症",
    "It Knows No Shore": "它不知道海岸",
    "Matter Matters": "重要事项",
    "Micro to Macro": "从微观到宏观",
    "Oops, My Pseudopod Slipped": "哎呀，我的假脚滑了",
    "Peer Review Not Required": "不需要同行评议",
    "Pseudopod-ful of Biomatter": "充满生物物质的假足",
    "Recontainment": "再封锁",
    "Splice of Life": "生命的拼接",
    "Sunseeker": "圣汐",
    "Survival of the Fittest (Not Your Enemies)": "适者生存（不是你的敌人）",
    "The End?": "结局？",
    "The Quiet Cure": "安静的治疗",
    "The Red Trail": "红色小径",
    "The Surface Beckons": "水面在召唤",
    "This Is How You Get Superpowers": "这就是你获得超能力的方式",
    "Too Big for Boxes": "盒子太大",
    "Unnatural Selection": "不自然的选择",
    "Violence Is Occasionally The Answer": "暴力有时是解决办法",
    "Well, They Started It": "好吧，是他们挑起的",
    "You Are Become Death": "你变成了死神",
    "Hunger": "饥饿",
    "FEED": "喂食",
    "The journey is long. The BODY tires. Seek SUSTENANCE.": "路途漫长。身体疲倦了。寻找食物。",
    "Unlocks FLESH. Unlocks SCAVENGING.": "解锁肉体。解锁拾荒。",
    "Affects:": "影响:",
    "BODY": "身体",
    "BIOMATTER Scavenging Speed": "生物物质拾荒速度",
    "Combat Max Health [via VIT]": "战斗最大生命值[通过 活力]",
    "Combat VITALITY": "战斗活力",
    "Endoplasm": "内质",
    "Resources": "资源",
    "Scavenge": "拾荒",
    "UNICELLULAR": "单细胞",
    "Scavenging...": "拾荒中...",
    "Explored Area Remaining Resources:": "探索区域剩余资源:",
    "Ciliate Protozoan": "纤毛原生动物",
    "Fast approaching entity. Appears hostile.": "快速接近的实体。看起来很有敌意。",
    "Ciliary Sweep": "纤毛扫荡",
    "Deal 3 consecutive hits of [0.3×DEX] PHYS damage.": "造成连续3次[0.3×灵巧]的物理伤害。",
    "/s": "/秒",
    "Peril ahead. Must forge STRENGTH. MASTERY is key.": "前方有危险。必须锻造力量。精通是关键。",
    "Threats": "风险",
    "TRAIN": "训练",
    "Unlocks LIMBS. Unlocks MOVESETS.": "解锁肢体。解锁招式集。",
    "(NEW!)": "(新!)",
    "STRENGTH": "力量",
    "Combat": "战斗",
    "MISC. STATS": "其它属性",
    "Add to Moveset": "添加到招式集",
    "AP Regen per Sec.": "每秒回复AP",
    "Available Moves": "可用招式",
    "Base Cooldown:": "基础冷却时间:",
    "Combat PHYS Crit. Damage [via POWER]": "战斗物理暴击。伤害[通过 能量]",
    "Combat POWER": "战力",
    "Current Moveset (": "当前招式集(",
    "Edit Moveset": "编辑招式集",
    "Move Cooldown Speed Boost": "移动冷却速度提升",
    "Phys Crit. Chance": "物理暴击。概率",
    "Phys Crit. Damage": "物理暴击。伤害",
    "Pseudopodia": "伪足",
    "Remove from Moveset": "移出招式集",
    "Select a move to view details.": "选择招式查看详情",
    "Moveset Full!": "招式集已满！",
    "Continue on. Skips for remaining run.": "继续。跳过剩余的运行。",
    "EXERT PRESSURE. SHATTER IT.": "施加压力。击碎它。",
    "Fracture": "断裂",
    "In Another Life": "另一种生活",
    "Prepare": "准备",
    "Requires 25 BODY. Unlocks shortcut.": "需要25个身体。解锁快捷方式。",
    "Requires immense force.": "需要巨大的力量。",
    "Weakness. In the glass. A quick escape?": "弱点。在玻璃杯里。快速逃离？",
    "Apex predator. Colossal and sturdy. Challenging.": "顶级捕食者。巨大而坚固。具有挑战性。",
    "Consider": "考虑一下",
    "Damage the enemy with PURE dmg and heal self for [0.2×VIT] per second over 10 seconds.": "对敌人造成纯伤害并治疗自己，持续[0.2×VIT] /秒，持续10秒",
    "Engulf": "吞噬",
    "Giant Amoeba": "巨型变形虫",
    "MOVESET": "招式集",
    "wisely.": "明智地。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "AP Cost:": "AP成本:",
    "Max AP:": "AP上限:",
    "Max HP:": "生命值上限:",
    "VIT": "活力",
    "PWR": "能量",
    "MND": "心灵",
    "HP:": "生命值:",
    "FOR": "FOR",
    "AP:": "AP:",
    "ACU": "精准",
    "DEX": "灵巧",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "You are": "你是",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) AP$/, '$1 AP'],
    [/^([\d\.,]+) cm³$/, '$1 cm³'],
    [/^([\d\.,]+)s ago$/, '$1 秒前'],
    [/^Defeat ([\d\.,]+) enemies$/, '击败 $1 敌人'],
    [/^Escape Area ([\d\.,]+)$/, '逃离区域 $1'],
    [/^Spend (.+) Biomatter in Total$/, '总共花费 $1 生物物质'],
    [/^Spend (.+) Mutagen in Total$/, '总共花费 $1 诱变剂'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);